-- MySQL Script generated by MySQL Workbench
-- Mon Sep 22 21:43:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `BookID` VARCHAR(50) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Author` VARCHAR(100) NOT NULL,
  `Category` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`BookID`),
  UNIQUE INDEX `idBooks_UNIQUE` (`BookID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Library`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Library` (
  `LocationID` INT NOT NULL,
  `Location` VARCHAR(100) NOT NULL,
  `Category` VARCHAR(100) NOT NULL,
  `BookID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`LocationID`),
  UNIQUE INDEX `idLibrary_UNIQUE` (`LocationID` ASC) VISIBLE,
  UNIQUE INDEX `BookID_UNIQUE` (`BookID` ASC) VISIBLE,
  CONSTRAINT `BookID`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Books` (`BookID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Members` (
  `MemberID` INT NOT NULL,
  `Name` VARCHAR(200) NOT NULL,
  `Address` VARCHAR(250) NOT NULL,
  `Mobile No.` INT NOT NULL,
  PRIMARY KEY (`MemberID`),
  UNIQUE INDEX `idMembers_UNIQUE` (`MemberID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans` (
  `LoanID` INT NOT NULL,
  `BookID` VARCHAR(50) NOT NULL,
  `MemberID` INT NOT NULL,
  `no of days` VARCHAR(45) NOT NULL,
  `Librarian` VARCHAR(45) NOT NULL,
  `Fee` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LoanID`),
  UNIQUE INDEX `idLoans_UNIQUE` (`LoanID` ASC) VISIBLE,
  UNIQUE INDEX `BookID_UNIQUE` (`BookID` ASC) VISIBLE,
  UNIQUE INDEX `MemberID_UNIQUE` (`MemberID` ASC) VISIBLE,
  CONSTRAINT `BookID`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Books` (`BookID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MemberID`
    FOREIGN KEY (`MemberID`)
    REFERENCES `mydb`.`Members` (`MemberID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
